In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

In [136]:
train_data = pd.read_csv('../input/hackerearth-carnival-wars-challenge/train.csv')
train_data.head()

Product_id  Stall_no             instock_date  Market_Category  \
0  BRAE2NF6JA5GUEXG      37.0  2015-08-22 18:36:12.000                2   
1  TUNE8SFB6RJN2HSD      38.0  2016-03-27 21:19:13.000               24   
2  BRAEAR7WZPQGPBZU       9.0  2015-08-18 19:25:22.000              447   
3  WATDZ2ZQ8JPDHCTJ      50.0  2016-03-28 21:53:01.000               23   
4  JWSEBUKYQPMBZ3RK       7.0  2016-03-29 22:58:53.000               63   

  Customer_name Loyalty_customer Product_Category  Grade  Demand  \
0      Lillyann              Yes          Fashion      1      68   
1         Klynn              Yes          Fashion      0      51   
2         Ridge              Yes       Child_care      0      10   
3         Abran              Yes      Educational      2      48   
4        Dustyn              Yes           Repair      1      35   

   Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  \
0             0.0      376.0           11.0         2983.0         4713.0   
1             0.0      397.0           12.0         7495.0        10352.0   
2             0.0      250.0            9.0         5752.0         7309.0   
3             0.0      144.0           13.0         5090.0        20814.0   
4             1.0      211.0            4.0         2430.0         9261.0   

   Selling_Price  
0    4185.947700  
1    9271.490256  
2    6785.701362  
3   13028.917824  
4     906.553935

In [137]:
train_data.groupby(['Grade']).count()

Product_id  Stall_no  instock_date  Market_Category  Customer_name  \
Grade                                                                       
0            4380      4375          4380             4380           4220   
1             381       381           381              381            369   
2            1103      1103          1103             1103           1074   
3             504       504           504              504            494   

       Loyalty_customer  Product_Category  Demand  Discount_avail  charges_1  \
Grade                                                                          
0                  4380              4380    4380            4355       4244   
1                   381               381     381             380        365   
2                  1103              1103    1103            1093       1075   
3                   504               504     504             502        486   

       charges_2 (%)  Minimum_price  Maximum_price  Selling_Price  
Grade                                                              
0               4235           4360           4134           4351  
1                368            378            358            379  
2               1071           1091           1051           1095  
3                489            501            482            502

In [138]:
train_data.mode().iloc[0]

Product_id                 ABQEJ7YQTNQGMXZV
Stall_no                                 20
instock_date        2015-08-18 22:08:56.000
Market_Category                          23
Customer_name                             1
Loyalty_customer                        Yes
Product_Category                   Pet_care
Grade                                     0
Demand                                   93
Discount_avail                            0
charges_1                               284
charges_2 (%)                            14
Minimum_price                          1891
Maximum_price                          2978
Selling_Price                       2356.17
Name: 0, dtype: object

In [5]:
fig = px.box(train_data , x = 'Product_Category' , y = 'charges_1')
fig.show()

In [6]:
fig = px.box(train_data , x = 'Product_Category' , y = 'Selling_Price')
fig.show()

In [7]:
fig = px.box(train_data , x = 'Product_Category' , y = 'charges_2 (%)')
fig.show()

In [8]:
fig = px.box(train_data , x = 'Product_Category' , y = 'Minimum_price')
fig.show()

In [9]:
fig = px.box(train_data , x = 'Product_Category' , y = 'Maximum_price')
fig.show()

In [139]:
train_data.isnull().sum()

Product_id            0
Stall_no              5
instock_date          0
Market_Category       0
Customer_name       211
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail       38
charges_1           198
charges_2 (%)       205
Minimum_price        38
Maximum_price       343
Selling_Price        41
dtype: int64

In [140]:
train_data['Stall_no'] = train_data['Stall_no'].fillna(train_data['Stall_no'].mode()[0])
train_data['Discount_avail'] = train_data['Discount_avail'].fillna(train_data['Discount_avail'].mode()[0])
train_data['charges_1'] = train_data['charges_1'].fillna(train_data['charges_1'].mean())
train_data['charges_2 (%)'] = train_data['charges_2 (%)'].fillna(train_data['charges_2 (%)'].mean())
train_data['Minimum_price'] = train_data['Minimum_price'].fillna(train_data['Minimum_price'].mean())
train_data['Maximum_price'] = train_data['Maximum_price'].fillna(train_data['Maximum_price'].mean())
train_data['Selling_Price'] = train_data['Selling_Price'].fillna(train_data['Selling_Price'].mean())

In [141]:
train_data['instock_date'] = pd.to_datetime(train_data['instock_date'])
train_data['year'] = train_data['instock_date'].dt.year

In [142]:
train_data['instock_date'] = pd.to_datetime(train_data['instock_date'])
train_data['month'] = train_data['instock_date'].dt.month

In [143]:
train_data.isnull().sum()

Product_id            0
Stall_no              0
instock_date          0
Market_Category       0
Customer_name       211
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail        0
charges_1             0
charges_2 (%)         0
Minimum_price         0
Maximum_price         0
Selling_Price         0
year                  0
month                 0
dtype: int64

In [144]:
test_data = pd.read_csv('../input/hackerearth-carnival-wars-challenge/test.csv')
test_data.head()

Product_id  Stall_no             instock_date  Market_Category  \
0  SCHE4YSTDVPVZVXW      39.0  2016-01-13 07:45:08.000              205   
1  ACCEGCATKHNRXUHW      49.0  2015-08-23 20:37:05.000                3   
2  NKCE6GJ5XVJDXNNZ       1.0  2015-11-14 18:12:39.000              183   
3  NKCEB8BK3ZXDHDHM       8.0  2015-11-21 04:56:19.000              358   
4  TOPEFDXSAHRNPF94      33.0  2015-05-06 15:09:46.000              167   

  Customer_name Loyalty_customer Product_Category  Grade  Demand  \
0        Ivanka              No           Fashion      0      90   
1         Isaak              Yes          Fashion      0      87   
2      Analiese              No        Technology      2      55   
3         Rusty              Yes       Child_care      3      86   
4        Eloise              No        Technology      0      27   

   Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  
0               0      380.0           16.0         2576.0           3340  
1               0      393.0           16.0         1202.0           1955  
2               0      493.0            9.0         7175.0          15715  
3               0      303.0           16.0         5404.0          13078  
4               0      567.0           16.0         4069.0           6244

In [145]:
test_data.isnull().sum()

Product_id           0
Stall_no             1
instock_date         0
Market_Category      0
Customer_name       53
Loyalty_customer     0
Product_Category     0
Grade                0
Demand               0
Discount_avail       0
charges_1           36
charges_2 (%)        5
Minimum_price       14
Maximum_price        0
dtype: int64

In [146]:
test_data['Stall_no'] = test_data['Stall_no'].fillna(test_data['Stall_no'].mode()[0])
test_data['Discount_avail'] = test_data['Discount_avail'].fillna(test_data['Discount_avail'].mode()[0])
test_data['charges_1'] = test_data['charges_1'].fillna(test_data['charges_1'].mean())
test_data['charges_2 (%)'] = test_data['charges_2 (%)'].fillna(test_data['charges_2 (%)'].mean())
test_data['Minimum_price'] = test_data['Minimum_price'].fillna(test_data['Minimum_price'].mean())
test_data['Maximum_price'] = test_data['Maximum_price'].fillna(test_data['Maximum_price'].mean())
test_data['instock_date'] = pd.to_datetime(test_data['instock_date'])
test_data['year'] = test_data['instock_date'].dt.year
test_data['instock_date'] = pd.to_datetime(test_data['instock_date'])
test_data['month'] = test_data['instock_date'].dt.month

In [147]:
test_data.isnull().sum()

Product_id           0
Stall_no             0
instock_date         0
Market_Category      0
Customer_name       53
Loyalty_customer     0
Product_Category     0
Grade                0
Demand               0
Discount_avail       0
charges_1            0
charges_2 (%)        0
Minimum_price        0
Maximum_price        0
year                 0
month                0
dtype: int64

In [148]:
train_id = train_data['Product_id']

In [149]:
train_id.head()

0    BRAE2NF6JA5GUEXG
1    TUNE8SFB6RJN2HSD
2    BRAEAR7WZPQGPBZU
3    WATDZ2ZQ8JPDHCTJ
4    JWSEBUKYQPMBZ3RK
Name: Product_id, dtype: object

In [150]:
x_train = train_data.iloc[:,[1,3,5,6,7,8,9 ,11,12,13,15 ,16 ]].values
y_train = train_data.iloc[:,14].values

In [151]:
x_train


array([[37.0, 2, 'Yes', ..., 4713.0, 2015, 8],
       [38.0, 24, 'Yes', ..., 10352.0, 2016, 3],
       [9.0, 447, 'Yes', ..., 7309.0, 2015, 8],
       ...,
       [36.0, 358, 'No ', ..., 14614.0, 2015, 11],
       [27.0, 452, 'Yes', ..., 5849.0, 2015, 12],
       [11.0, 58, 'Yes', ..., 5383.0, 2016, 1]], dtype=object)

In [152]:
x_test = test_data.iloc[:,[1,3,5,6,7,8,9 ,11,12,13 ,14 , 15]].values

In [153]:
test_id = test_data['Product_id']

In [154]:
x_test

array([[39.0, 205, 'No ', ..., 3340, 2016, 1],
       [49.0, 3, 'Yes', ..., 1955, 2015, 8],
       [1.0, 183, 'No ', ..., 15715, 2015, 11],
       ...,
       [14.0, 106, 'Yes', ..., 10894, 2016, 3],
       [1.0, 104, 'Yes', ..., 5165, 2015, 5],
       [3.0, 165, 'No ', ..., 7506, 2015, 8]], dtype=object)

In [155]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le_train1 = LabelEncoder()
le_train2 = LabelEncoder()
x_train[:,2] = le_train1.fit_transform(x_train[:,2])
x_train[:,3] = le_train2.fit_transform(x_train[:,3])

In [156]:
x_train[:5,:]

array([[37.0, 2, 1, 3, 1, 68, 0.0, 11.0, 2983.0, 4713.0, 2015, 8],
       [38.0, 24, 1, 3, 0, 51, 0.0, 12.0, 7495.0, 10352.0, 2016, 3],
       [9.0, 447, 1, 0, 0, 10, 0.0, 9.0, 5752.0, 7309.0, 2015, 8],
       [50.0, 23, 1, 2, 2, 48, 0.0, 13.0, 5090.0, 20814.0, 2016, 3],
       [7.0, 63, 1, 8, 1, 35, 1.0, 4.0, 2430.0, 9261.0, 2016, 3]],
      dtype=object)

In [157]:
x_train[:,3]

array([3, 3, 0, ..., 8, 8, 9], dtype=object)

In [158]:
le_test1 = LabelEncoder()
le_test2 = LabelEncoder()
x_test[:,2] = le_test1.fit_transform(x_test[:,2])
x_test[:,3] = le_test2.fit_transform(x_test[:,3])

In [159]:
x_test.shape

(3430, 12)

In [160]:
x_train.shape

(6368, 12)

In [161]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [162]:
x_train

array([[ 0.81649959, -1.15903947,  0.79892518, ..., -0.47574736,
        -0.65760946,  0.47812147],
       [ 0.88631737, -1.02982699,  0.79892518, ...,  1.08439672,
         1.40121899, -1.02527451],
       [-1.13839813,  1.45457648,  0.79892518, ...,  0.24248886,
        -0.65760946,  0.47812147],
       ...,
       [ 0.74668182,  0.93185329, -1.25168166, ...,  2.26356573,
        -0.65760946,  1.38015906],
       [ 0.11832183,  1.48394295,  0.79892518, ..., -0.16144984,
        -0.65760946,  1.68083826],
       [-0.99876258, -0.83013499,  0.79892518, ..., -0.29037822,
         1.40121899, -1.6266329 ]])

In [163]:
from sklearn.model_selection import GridSearchCV , RandomizedSearchCV , train_test_split
from sklearn.model_selection import ShuffleSplit
from sklearn.linear_model import LinearRegression  
from sklearn.tree import DecisionTreeRegressor  , ExtraTreeRegressor
from sklearn.ensemble import RandomForestRegressor , AdaBoostRegressor , VotingRegressor 
from sklearn.svm import SVR
from xgboost import XGBRegressor
from tpot import TPOTRegressor
import lightgbm as lgb

In [195]:
regressor = TPOTRegressor(generations=5, population_size=20, cv=5,
                                    random_state=42, verbosity=2)
regressor.fit(x_train,y_train)

KeyboardInterrupt: 

In [190]:
predictions = regressor.predict(x_test)
predictions

array([ 3154.43080308,  1825.27282051, 11551.97023328, ...,
        6561.3130609 ,  3517.31898271,  1258.98929213])

In [191]:
data = pd.DataFrame((zip(test_id,predictions)),columns=['Product_id','Selling_Price'])
data

Product_id  Selling_Price
0     SCHE4YSTDVPVZVXW    3154.430803
1     ACCEGCATKHNRXUHW    1825.272821
2     NKCE6GJ5XVJDXNNZ   11551.970233
3     NKCEB8BK3ZXDHDHM    9449.851809
4     TOPEFDXSAHRNPF94    5750.966734
...                ...            ...
3425  BBAE9K7BXFUTDNBK    3975.352069
3426  RTRDYPA4PJHCJCGF    9160.294368
3427  TUNE8FWQBS7TVVT7    6561.313061
3428  NKCEGMUABCRGUZPE    3517.318983
3429  RNGE7M92KAQWUBCS    1258.989292

[3430 rows x 2 columns]

In [192]:
data[data['Selling_Price'] < 0]

Empty DataFrame
Columns: [Product_id, Selling_Price]
Index: []

In [193]:
data.to_csv('my_submission.csv',index= False)
